title: Rizuke's Blog
email: contact@rizuke.dev
description: >- # this means to ignore newlines until "baseurl:"
  A place where I describe various things from my dev life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rizuke.dev" # the base hostname & protocol for your site, e.g. http://example.com
github_username: rizuke

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

minima:
  skin: dark