title: Rizuke's Blog
email: contact@rizuke.dev
description: >-
  The place where I describe things I'm learning or fun projects I'm working on.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rizuke.dev"

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/rizuke" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/razvan-romanescu/" }

google_analytics: G-54TYQCZFEV